[package]
name = "caesium-daemon"
version = "0.1.0"
authors = ["Will Daly"]

[dependencies]
caesium-core = { path = "../caesium-core" }
clap = "2.32.0"
env_logger = "0.5.10"
lazy_static = "1.0.2"
log = "0.4"
regex = "1"
slab = "0.4"
