[package]
name = "caesium"
version = "0.1.0"
authors = ["Will Daly"]

[dependencies]
rand = "0.4"
bincode = "1.0.0"
serde = "1.0.65"
serde_derive = "1.0.65"
bencher = "0.1.5"

[[bench]]
name = "quantile"
harness = false

[profile.release]
debug = true
