timeout: 1200s
options:
  machineType: N1_HIGHCPU_32
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/hairy-coo-0002/caesium-server:$TAG_NAME',
    '-f', 'caesium-server/Dockerfile',
    '.']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/hairy-coo-0002/caesium-daemon:$TAG_NAME',
    '-f', 'caesium-daemon/Dockerfile',
    '.']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/hairy-coo-0002/caesium-load:$TAG_NAME',
    '-f', 'caesium-load/Dockerfile',
    '.']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/hairy-coo-0002/caesium-cli:$TAG_NAME',
    '-f', 'caesium-cli/Dockerfile',
    '.']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/hairy-coo-0002/caesium-server-baseline:$TAG_NAME',
    '-f', 'caesium-server/Dockerfile',
    '--build-arg', 'features=baseline',
    '.']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'gcr.io/hairy-coo-0002/caesium-daemon-baseline:$TAG_NAME',
    '-f', 'caesium-daemon/Dockerfile',
    '--build-arg', 'features=baseline',
    '.']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/hairy-coo-0002/caesium-cli-baseline:$TAG_NAME',
    '-f', 'caesium-cli/Dockerfile',
    '--build-arg', 'features=baseline',
    '.']
  waitFor: ['-']
images: [
    'gcr.io/hairy-coo-0002/caesium-server:$TAG_NAME',
    'gcr.io/hairy-coo-0002/caesium-daemon:$TAG_NAME',
    'gcr.io/hairy-coo-0002/caesium-load:$TAG_NAME',
    'gcr.io/hairy-coo-0002/caesium-cli:$TAG_NAME',
    'gcr.io/hairy-coo-0002/caesium-server-baseline:$TAG_NAME',
    'gcr.io/hairy-coo-0002/caesium-daemon-baseline:$TAG_NAME',
    'gcr.io/hairy-coo-0002/caesium-cli-baseline:$TAG_NAME',
]
