[package]
name = "caesium-core"
version = "0.1.0"
authors = ["Will Daly"]

[dependencies]
bencher = "0.1.5"
clap = "2.32.0"
rand = "0.4"
slab = "0.4"

[[bench]]
name = "quantile"
harness = false

[profile.release]
debug = true
