[package]
name = "caesium-core"
version = "0.1.0"
authors = ["Will Daly"]

[dependencies]
bencher = "0.1.5"
bitpacking = "0.5.1"
clap = "2.32.0"
rand = "0.5.4"
slab = "0.4"

[features]
baseline = []

[[bench]]
name = "quantile"
harness = false

[profile.release]
debug = true
