[package]
name = "caesium-cli"
version = "0.1.0"
authors = ["Will Daly"]

[dependencies]
caesium-core = { path = "../caesium-core" }
clap = "2.32.0"
rand = "0.5.4"
rustyline = "1.0.0"

[features]
baseline = ["caesium-core/baseline"]
nosampler = ["caesium-core/nosampler"]
